stages:
    - build
    - test
    - push
    - deploy


build_Job:
    stage: build
    script:
        - docker build -t todo-react-app:latest -f HealthyApp .
        - echo "Docker image build successfully"
    tags:
        - aws-test

test_Job:
    stage: test
    script:
        - echo "There is no tests"
    tags:
        - aws-test

push_Job:
    stage: push
    script:
        - docker image tag todo-react-app:latest $DOCKER_USER/todo-react-app:latest
        - echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
        - docker push $DOCKER_USER/todo-react-app:latest
        - echo "Image push successfully"
    tags:
        - aws-test

deploy_Job:
    stage: deploy
    script:
        - docker run -d -p 5173:5173 todo-react-app:latest
        - echo "Application running successfully on port of 5173"
    tags:
        - aws-test
        

