pipeline{
    agent {label 'test'}
    
    stages{
        stage("Code"){
            steps{
                git url: "https://github.com/sunnyshinde123/ToDoApp_By_React.git", branch:"$branch"
                echo "project clonned successfully"
            }
        }
        stage("Test"){
            steps{
                echo  "This is the test stage"
            }
        }
        stage("Build"){
            steps{
                sh "docker build -t todo-react-app:latest HealthyApp/"
                echo "Image builded successfully"
            }
        }
        stage("Push to Hub"){
            steps{
                withCredentials([usernamePassword(
                    credentialsId: "DockerHub",
                    usernameVariable: "DockerHubUser",
                    passwordVariable: "DockerHubPass")]){
                        
                        sh "echo $DockerHubPass | docker login -u ${env.DockerHubUser} --password-stdin"
                        sh "docker image tag todo-react-app:latest ${env.DockerHubUser}/todo-react-app:latest"
                        sh "docker push ${env.DockerHubUser}/todo-react-app:latest"
                        echo "Image Push to hub successfully"
                    }
            }
        }
        stage("Deploy"){
            steps{
                sh "docker run -d -p 5173:5173 todo-react-app:latest"
                echo "Application running"
            }
        }
    }
}
